### ISSUE TITLE
Charts not be displaying

### ISSUE THREAD

**Issue by NaumukS** [unfoldadmin/formula#10]
Why might charts not be displaying properly?In settings js/css connected
![image](https://github.com/unfoldadmin/formula/assets/67160238/b2dba47f-1e5a-450f-a3c8-aeac22879116)
![image](https://github.com/unfoldadmin/formula/assets/67160238/6679ce6d-9b7c-4540-9ff1-8e721fea3b8f)

**Comment by lukasvinclav** [comment]
How I can reproduce the issue? Demo site looks okay:

https://demo.unfoldadmin.com/admin/
