### ISSUE TITLE
Optional demo data

### ISSUE THREAD

**Issue by Mte90** [unfoldadmin/formula#3]
They can be useful to test it and see the appearance of the various models and how works.

**Comment by lukasvinclav** [comment]
Fixtures with some demo content will be enough?

https://docs.djangoproject.com/en/4.2/topics/db/fixtures/

**Comment by Mte90** [comment]
I think so, the important is to try it after all and there are data.

**Comment by lukasvinclav** [comment]
Fixtures are now part of the projects.
